# Disease Prediction based on Symtoms

In [1]:
#Importing Libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn import tree
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score, precision_score

# Train the Models using Selected Features

In [2]:
#Reading the training .csv file
df=pd.read_csv("data/Training.csv")
DF= pd.read_csv('data/Training.csv', index_col='prognosis')
#Replace the values in the imported file by pandas by the inbuilt function replace in pandas.

df = df.drop('Unnamed: 133', axis=1)
df.head()
#DF.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [4]:
#X= df[l1]
X = df.iloc[:,:-1]
print(type(X))
print(X)

<class 'pandas.core.frame.DataFrame'>
      itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0
1           0          1                     1                    0
2           1          0                     1                    0
3           1          1                     0                    0
4           1          1                     1                    0
...       ...        ...                   ...                  ...
4915        0          0                     0                    0
4916        0          1                     0                    0
4917        0          0                     0                    0
4918        0          1                     0                    0
4919        0          1                     0                    0

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0
1             0       0           0             0        0                 0
2             0       0           0             0        0                 0
3             0       0           0             0        0                 0
4             0       0           0             0        0                 0
...         ...     ...         ...           ...      ...               ...
4915          0       0           0             0        0                 0
4916          0       0           0             0        0                 0
4917          0       0           0             0        0                 0
4918          0       0           1             0        0                 0
4919          0       0           0             0        0                 0

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0
1     ...                   0           0         0             0
2     ...                   0           0         0             0
3     ...                   0           0         0             0
4     ...                   0           0         0             0
...   ...                 ...         ...       ...           ...
4915  ...                   0           0         0             0
4916  ...                   1           1         1             0
4917  ...                   0           0         0             0
4918  ...                   0           0         0             1
4919  ...                   0           0         0             0

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0
1                       0                     0                   0        0
2                       0                     0                   0        0
3                       0                     0                   0        0
4                       0                     0                   0        0
...                   ...                   ...                 ...      ...
4915                    0                     0                   0        0
4916                    0                     0                   0        0
4917                    0                     0                   0        0
4918                    1                     1                   1        0
4919                    0                     0                   0        1

      red_sore_around_nose  yellow_crust_ooze
0                        0                  0
1                        0                  0
2                        0                  0
3                        0                  0
4                        0                  0
...                    ...                ...
4915                     0                  0
4916                     0                  0
4917                     0                  0
4918                     0                  0
4919                     1                  1

[4920 rows x 132 columns]

In [5]:
y = df[["prognosis"]]
y = np.ravel(y)

# label encode the target variable
le = LabelEncoder()
y = le.fit_transform(y)

print(type(y))
print(y)

<class 'numpy.ndarray'>
[15 15 15 ... 38 35 27]

In [6]:
#Reading the  testing.csv file
tr=pd.read_csv("data/Testing.csv")

tr.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction

In [7]:
X_test_csv= tr.iloc[:,:-1]

y_test_csv = tr[["prognosis"]]
y_test_csv = np.ravel(y_test_csv)
y_test_csv = le.transform(y_test_csv)
print(X_test_csv)

    itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0         1          1                     1                    0          0
1         0          0                     0                    1          1
2         0          0                     0                    0          0
3         1          0                     0                    0          0
4         1          1                     0                    0          0
5         0          0                     0                    0          0
6         0          0                     0                    0          0
7         0          0                     0                    0          0
8         0          0                     0                    0          0
9         0          0                     0                    0          0
10        0          0                     0                    0          0
11        0          0                     0                    0          0
12        0          0                     0                    0          0
13        0          0                     0                    0          0
14        1          0                     0                    0          0
15        0          0                     0                    0          0
16        1          1                     0                    0          0
17        0          1                     0                    0          0
18        0          0                     0                    0          0
19        0          0                     0                    0          0
20        1          0                     0                    0          0
21        0          0                     0                    0          0
22        0          0                     0                    0          0
23        0          0                     0                    0          0
24        0          0                     0                    0          0
25        0          0                     0                    0          0
26        0          0                     0                    1          0
27        0          0                     0                    0          0
28        0          0                     0                    0          0
29        0          0                     0                    0          0
30        0          0                     0                    0          0
31        0          0                     0                    0          0
32        0          0                     0                    0          0
33        0          0                     0                    0          0
34        0          0                     0                    0          0
35        0          0                     0                    0          0
36        0          0                     0                    0          0
37        0          1                     0                    0          0
38        0          0                     0                    0          0
39        0          1                     0                    0          0
40        0          1                     0                    0          0
41        1          1                     0                    0          0

    chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0        0           0             0        0                 0  ...
1        1           0             0        0                 0  ...
2        0           0             1        1                 1  ...
3        0           0             0        0                 0  ...
4        0           0             1        0                 0  ...
5        0           0             0        0                 0  ...
6        0           0             0        0                 0  ...
7        0           0             0        0                 0  ...
8        0           0             0        0                 0  ...
9        0           0             0        0                 0  ...
10       0           0             0        0                 0  ...
11       0           0             0        1                 0  ...
12       0           0             0        0                 0  ...
13       0           0             0        0                 0  ...
14       0           0             0        0                 0  ...
15       1           0             0        0                 0  ...
16       0           0             0        0                 0  ...
17       1           1             0        0                 0  ...
18       1           0             0        0                 0  ...
19       0           1             0        0                 0  ...
20       0           0             0        0                 0  ...
21       0           0             0        0                 0  ...
22       0           1             0        0                 0  ...
23       0           1             0        0                 0  ...
24       0           0             0        0                 0  ...
25       1           0             0        0                 0  ...
26       1           0             0        0                 0  ...
27       1           0             0        0                 0  ...
28       0           0             0        0                 0  ...
29       0           0             0        0                 0  ...
30       0           0             0        0                 0  ...
31       0           0             0        0                 0  ...
32       0           0             0        0                 0  ...
33       0           0             0        0                 0  ...
34       0           1             0        0                 0  ...
35       0           0             0        0                 0  ...
36       0           0             0        0                 0  ...
37       0           0             0        0                 0  ...
38       0           0             0        0                 0  ...
39       0           1             0        0                 0  ...
40       0           0             0        0                 0  ...
41       0           0             0        0                 0  ...

    pus_filled_pimples  blackheads  scurring  skin_peeling  \
0                    0           0         0             0
1                    0           0         0             0
2                    0           0         0             0
3                    0           0         0             0
4                    0           0         0             0
5                    0           0         0             0
6                    0           0         0             0
7                    0           0         0             0
8                    0           0         0             0
9                    0           0         0             0
10                   0           0         0             0
11                   0           0         0             0
12                   0           0         0             0
13                   0           0         0             0
14                   0           0         0             0
15                   0           0         0             0
16                   0           0         0             0
17                   0           0         0             0
18                   0           0         0             0
19                   0           0         0             0
20                   0           0         0             0
21                   0           0         0             0
22                   0           0         0             0
23                   0           0         0             0
24                   0           0         0             0
25                   0           0         0             0
26                   0           0         0             0
27                   0           0         0             0
28                   0           0         0             0
29                   0           0         0             0
30                   0           0         0             0
31                   0           0         0             0
32                   0           0         0             0
33                   0           0         0             0
34                   0           0         0             0
35                   0           0         0             0
36                   0           0         0             0
37                   1           1         1             0
38                   0           0         0             0
39                   0           0         0             1
40                   0           0         0             0
41                   0           0         0             1

    silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                     0                     0                   0        0
1                     0                     0                   0        0
2                     0                     0                   0        0
3                     0                     0                   0        0
4                     0                     0                   0        0
5                     0                     0                   0        0
6                     0                     0                   0        0
7                     0                     0                   0        0
8                     0                     0                   0        0
9                     0                     0                   0        0
10                    0                     0                   0        0
11                    0                     0                   0        0
12                    0                     0                   0        0
13                    0                     0                   0        0
14                    0                     0                   0        0
15                    0                     0                   0        0
16                    0                     0                   0        0
17                    0                     0                   0        0
18                    0                     0                   0        0
19                    0                     0                   0        0
20                    0                     0                   0        0
21                    0                     0                   0        0
22                    0                     0                   0        0
23                    0                     0                   0        0
24                    0                     0                   0        0
25                    0                     0                   0        0
26                    0                     0                   0        0
27                    0                     0                   0        0
28                    0                     0                   0        0
29                    0                     0                   0        0
30                    0                     0                   0        0
31                    0                     0                   0        0
32                    0                     0                   0        0
33                    0                     0                   0        0
34                    0                     0                   0        0
35                    0                     0                   0        0
36                    0                     0                   0        0
37                    0                     0                   0        0
38                    0                     0                   0        0
39                    1                     1                   1        0
40                    0                     0                   0        1
41                    0                     0                   0        0

    red_sore_around_nose  yellow_crust_ooze
0                      0                  0
1                      0                  0
2                      0                  0
3                      0                  0
4                      0                  0
5                      0                  0
6                      0                  0
7                      0                  0
8                      0                  0
9                      0                  0
10                     0                  0
11                     0                  0
12                     0                  0
13                     0                  0
14                     0                  0
15                     0                  0
16                     0                  0
17                     0                  0
18                     0                  0
19                     0                  0
20                     0                  0
21                     0                  0
22                     0                  0
23                     0                  0
24                     0                  0
25                     0                  0
26                     0                  0
27                     0                  0
28                     0                  0
29                     0                  0
30                     0                  0
31                     0                  0
32                     0                  0
33                     0                  0
34                     0                  0
35                     0                  0
36                     0                  0
37                     0                  0
38                     0                  0
39                     0                  0
40                     1                  1
41                     1                  0

[42 rows x 132 columns]

In [8]:
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, train_size = 0.70, random_state=42)

In [9]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

**To select the top 95 features, we used RFE with Random Forest as an estimator**

In [10]:
rfc = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, n_jobs=-1)
n_features = 95
rfe = RFE(estimator=rfc, n_features_to_select=n_features)
X_train_rfe = rfe.fit_transform(X_train, y_train)
X_test_rfe = rfe.transform(X_test)
X_test_csv_rfe = rfe.transform(X_test_csv)

In [11]:
# Get the names of the selected features
selected_feature_names = df.columns[:-1][rfe.support_]
selected_feature_names = list(selected_feature_names)
selected_feature_names = [feature.replace('_', ' ') for feature in selected_feature_names]
print("Selected features:", selected_feature_names)

Selected features: ['itching', 'nodal skin eruptions', 'shivering', 'chills', 'joint pain', 'stomach pain', 'spotting  urination', 'weight gain', 'cold hands and feets', 'weight loss', 'restlessness', 'patches in throat', 'irregular sugar level', 'sweating', 'indigestion', 'dark urine', 'nausea', 'loss of appetite', 'pain behind the eyes', 'back pain', 'constipation', 'abdominal pain', 'diarrhoea', 'mild fever', 'yellowing of eyes', 'swelling of stomach', 'swelled lymph nodes', 'malaise', 'phlegm', 'throat irritation', 'redness of eyes', 'sinus pressure', 'runny nose', 'congestion', 'chest pain', 'weakness in limbs', 'fast heart rate', 'neck pain', 'dizziness', 'cramps', 'bruising', 'obesity', 'swollen legs', 'enlarged thyroid', 'brittle nails', 'swollen extremeties', 'slurred speech', 'knee pain', 'hip joint pain', 'muscle weakness', 'stiff neck', 'swelling joints', 'movement stiffness', 'spinning movements', 'loss of balance', 'unsteadiness', 'weakness of one body side', 'loss of smell', 'bladder discomfort', 'continuous feel of urine', 'passage of gases', 'internal itching', 'toxic look (typhos)', 'depression', 'irritability', 'muscle pain', 'altered sensorium', 'red spots over body', 'belly pain', 'abnormal menstruation', 'dischromic  patches', 'watering from eyes', 'increased appetite', 'polyuria', 'family history', 'mucoid sputum', 'rusty sputum', 'lack of concentration', 'visual disturbances', 'receiving blood transfusion', 'receiving unsterile injections', 'stomach bleeding', 'history of alcohol consumption', 'fluid overload.1', 'blood in sputum', 'prominent veins on calf', 'palpitations', 'painful walking', 'skin peeling', 'silver like dusting', 'small dents in nails', 'inflammatory nails', 'blister', 'red sore around nose', 'yellow crust ooze']

**To build the precision of the model, we utilized three distinctive algorithms which are as per the following**
* Decision Tree algorithm
* Random Forest algorithm
* KNearestNeighbour algorithm
* Naive Bayes algorithm

# Decision Tree Algorithm

In [12]:
from sklearn import tree

clf3 = tree.DecisionTreeClassifier(max_depth=37) 
clf3 = clf3.fit(X_train_rfe,y_train)

y_pred=clf3.predict(X_test_rfe)
print("Decision Tree")
print("Accuracy of Training.csv Split Data")
print("Accuracy score:", accuracy_score(y_test, y_pred))
print("Number of correct predictions:", accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Decision Tree
Accuracy of Training.csv Split Data
Accuracy score: 0.9579945799457995
Number of correct predictions: 1414
Confusion matrix
[[30  0  2 ...  0  0  0]
 [ 0 32  7 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  2 ... 34  0  0]
 [ 0  0  4 ...  0 33  0]
 [ 0  0  0 ...  0  0 39]]

In [13]:
y_pred=clf3.predict(X_test_csv_rfe)
print("Decision Tree")
print("Accuracy of Testing.csv")
print("Accuracy score:", accuracy_score(y_test_csv, y_pred))
print("Number of correct predictions:", accuracy_score(y_test_csv, y_pred, normalize=False))
print("Precision score:", precision_score(y_test_csv, y_pred, average='weighted', zero_division=1))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test_csv,y_pred)
print(conf_matrix)

Decision Tree
Accuracy of Testing.csv
Accuracy score: 0.9761904761904762
Number of correct predictions: 41
Precision score: 0.9880952380952381
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]

# Random Forest Algorithm

In [14]:
from sklearn.ensemble import RandomForestClassifier
clf4 = RandomForestClassifier(n_estimators=100)
clf4 = clf4.fit(X_train_rfe,y_train)

# calculating accuracy 
y_pred=clf4.predict(X_test_rfe)
print("Random Forest")
print("Accuracy of Training.csv Split Data")
print("Accuracy score:", accuracy_score(y_test, y_pred))
print("Number of correct predictions:", accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Random Forest
Accuracy of Training.csv Split Data
Accuracy score: 0.989159891598916
Number of correct predictions: 1460
Confusion matrix
[[32  0  0 ...  0  0  0]
 [ 0 32  7 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]

In [15]:
y_pred=clf4.predict(X_test_csv_rfe)
print("Random Forest")
print("Accuracy of Testing.csv")
print("Accuracy score:", accuracy_score(y_test_csv, y_pred))
print("Number of correct predictions:", accuracy_score(y_test_csv, y_pred, normalize=False))
print("Precision score:", precision_score(y_test_csv, y_pred, average='weighted', zero_division=1))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test_csv,y_pred)
print(conf_matrix)

Random Forest
Accuracy of Testing.csv
Accuracy score: 0.9761904761904762
Number of correct predictions: 41
Precision score: 0.9880952380952381
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]

# KNearestNeighbour Algorithm

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn=knn.fit(X_train_rfe,y_train)

y_pred=knn.predict(X_test_rfe)
print("kNearest Neighbour")
print("Accuracy of Training.csv Split Data")
print("Accuracy score:", accuracy_score(y_test, y_pred))
print("Number of correct predictions:", accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

kNearest Neighbour
Accuracy of Training.csv Split Data
Accuracy score: 0.989159891598916
Number of correct predictions: 1460
Confusion matrix
[[32  0  0 ...  0  0  0]
 [ 0 32  7 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]

In [17]:
y_pred=knn.predict(X_test_csv_rfe)
print("kNearest Neighbour")
print("Accuracy of Testing.csv")
print("Accuracy score:", accuracy_score(y_test_csv, y_pred))
print("Number of correct predictions:", accuracy_score(y_test_csv, y_pred, normalize=False))
print("Precision score:", precision_score(y_test_csv, y_pred, average='weighted', zero_division=1))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test_csv,y_pred)
print(conf_matrix)

kNearest Neighbour
Accuracy of Testing.csv
Accuracy score: 0.9761904761904762
Number of correct predictions: 41
Precision score: 0.9880952380952381
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]

# Naive Bayes Algorithm

In [18]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb=gnb.fit(X_train_rfe,y_train)


y_pred=gnb.predict(X_test_rfe)
print("Naive Bayes")
print("Accuracy of Training.csv Split Data")
print("Accuracy score:", accuracy_score(y_test, y_pred))
print("Number of correct predictions:", accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Naive Bayes
Accuracy of Training.csv Split Data
Accuracy score: 0.989159891598916
Number of correct predictions: 1460
Confusion matrix
[[32  0  0 ...  0  0  0]
 [ 0 32  7 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]

In [19]:
y_pred=gnb.predict(X_test_csv_rfe)
print("Naive Bayes")
print("Accuracy of Testing.csv")
print("Accuracy score:", accuracy_score(y_test_csv, y_pred))
print("Number of correct predictions:", accuracy_score(y_test_csv, y_pred, normalize=False))
print("Precision score:", precision_score(y_test_csv, y_pred, average='weighted', zero_division=1))

print("Confusion matrix")
conf_matrix=confusion_matrix(y_test_csv,y_pred)
print(conf_matrix)

Naive Bayes
Accuracy of Testing.csv
Accuracy score: 0.9761904761904762
Number of correct predictions: 41
Precision score: 0.9880952380952381
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]

# Support Vector Machine

In [20]:
from sklearn.svm import SVC
svc = SVC(gamma=100.0, C=1.0)
svc=svc.fit(X_train_rfe,y_train)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
y_pred=svc.predict(X_test_rfe)
print("Support Vector Machine")
print("Accuracy of Training.csv Split Data")
print("Accuracy score:", accuracy_score(y_test, y_pred))
print("Number of correct predictions:", accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Support Vector Machine
Accuracy of Training.csv Split Data
Accuracy score: 0.989159891598916
Number of correct predictions: 1460
Confusion matrix
[[32  0  0 ...  0  0  0]
 [ 0 32  7 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]

In [21]:
y_pred=svc.predict(X_test_csv_rfe)
print("Support Vector Machine")
print("Accuracy of Testing.csv")
print("Accuracy score:", accuracy_score(y_test_csv, y_pred))
print("Number of correct predictions:", accuracy_score(y_test_csv, y_pred, normalize=False))
print("Precision score:", precision_score(y_test_csv, y_pred, average='weighted', zero_division=1))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test_csv,y_pred)
print(conf_matrix)

Support Vector Machine
Accuracy of Testing.csv
Accuracy score: 0.9761904761904762
Number of correct predictions: 41
Precision score: 0.9880952380952381
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]

# Gradient Boosting

In [22]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier()
gbc=gbc.fit(X_train_rfe,y_train)

y_pred=gbc.predict(X_test_rfe)
print("Gradient Boosting")
print("Accuracy of Training.csv Split Data")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Gradient Boosting
Accuracy of Training.csv Split Data
0.989159891598916
1460
Confusion matrix
[[32  0  0 ...  0  0  0]
 [ 0 32  7 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]

In [23]:
y_pred=gbc.predict(X_test_csv_rfe)
print("Gradient Boosting")
print("Accuracy of Testing.csv")
print("Accuracy score:", accuracy_score(y_test_csv, y_pred))
print("Number of correct predictions:", accuracy_score(y_test_csv, y_pred, normalize=False))
print("Precision score:", precision_score(y_test_csv, y_pred, average='weighted', zero_division=1))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test_csv,y_pred)
print(conf_matrix)

Gradient Boosting
Accuracy of Testing.csv
Accuracy score: 0.9761904761904762
Number of correct predictions: 41
Precision score: 0.9880952380952381
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]